language: python
python: 3.7.4

install:
  - pip install -r Tools/JsonValidator/requirements.txt
  - pip install mypy


script:
  - python3 Tools/JsonValidator/JsonValidator.py --all
  - ./.travis/mypy.sh
