language: python
python: 3.6

install:
  - pip install -r Tools/JsonValidator/requirements.txt
  - pip install pylint


script:
  - python3 Tools/JsonValidator/validation.py --all
  - cores=$(nproc)
  - pylint -j $cores PublishedModules/*/*/*.py --exit-zero
