name: Skills Store Building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: combine install files
      run: |
        shopt -s nullglob
        skills='['
        for filepath in PublishedSkills/*/*/*.install; do
          skills+="$(cat $filepath),"
        done
        echo "${skills::-1}]" > store.json
    - name: zip skills and deploy
      run: |
        shopt -s nullglob
        for skillpath in PublishedSkills/*/*/*.install; do
          zip -r $(dirname "${skillpath}" | xargs basename) $skillpath
        done
    - name: deploy store.json
      uses: horochx/deploy-via-scp@master
      with:
        local: store.json
        remote: "${{ secrets.DOMAIN }}/assets/store"
        host: ${{ secrets.DOMAIN }}
        port: 22
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
    - name: deploy skills
      uses: horochx/deploy-via-scp@master
      with:
        local: "./*.zip"
        remote: "${{ secrets.DOMAIN }}/assets/skills"
        host: ${{ secrets.DOMAIN }}
        port: 22
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
        
        
        

